# Generated by Django 3.2 on 2023-02-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='short name'),
        ),
    ]
