# Generated by Django 3.2 on 2023-02-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20230206_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'short_name')},
        ),
    ]
