# Generated by Django 3.2 on 2023-02-06 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_auto_20230206_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='name')),
                ('last_name', models.CharField(max_length=60, verbose_name='last name')),
                ('job', models.CharField(choices=[('0', 'Engineer'), ('1', 'Accounter'), ('2', 'Salesman'), ('3', 'Others')], max_length=1, verbose_name='job')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
