# Generated by Django 3.2 on 2023-02-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='skill')),
            ],
            options={
                'verbose_name': 'Habilidades',
                'verbose_name_plural': 'Habilidades empleado',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(to='employees.Skill'),
        ),
    ]
