# Generated by Django 3.2 on 2023-02-14 17:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20230214_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=ckeditor.fields.RichTextField(default='text'),
            preserve_default=False,
        ),
    ]
